### ISSUE TITLE
createrun fails when HTTP response dictionary contains Int64 values

### ISSUE THREAD

**Issue by jaschau** [JuliaAI/MLFlowClient.jl#17]
I am creating a new run with the code below

```
mlf = MLFlow("http://localhost:5000")
mlf_experiment = getorcreateexperiment(mlf, "experiment_name")
mlf_run = createrun(
    mlf, 
    mlf_experiment, 
    tags=[
        Dict(
            "key" => "mlflow.runName",
            "value" => "run_name"
        )
    ]
)
```

which fails with the following error message:

```
ERROR: LoadError: MethodError: no method matching parse(::Type{Int64}, ::Int64)
Closest candidates are:
  parse(::Type{T}, ::AbstractChar; base) where T<:Integer at parse.jl:40
  parse(::Type{T}, ::AbstractString; base) where T<:Integer at parse.jl:240
  parse(::Type{T}, ::AbstractString; kwargs...) where T<:Real at parse.jl:379
Stacktrace:
 [1] MLFlowRunInfo(info::Dict{String, Any})
   @ MLFlowClient ~/.julia/packages/MLFlowClient/Yj8Aj/src/types.jl:124
 [2] MLFlowRun
   @ ~/.julia/packages/MLFlowClient/Yj8Aj/src/types.jl:224 [inlined]
 [3] createrun(mlf::MLFlow, experiment_id::Int64; start_time::Missing, tags::Vector{Dict{String, String}})
   @ MLFlowClient ~/.julia/packages/MLFlowClient/Yj8Aj/src/runs.jl:23
 [4] createrun(mlf::MLFlow, experiment::MLFlowExperiment; start_time::Missing, tags::Vector{Dict{String, String}})
   @ MLFlowClient ~/.julia/packages/MLFlowClient/Yj8Aj/src/runs.jl:30
```

I have fixed this by adding the following code before importing MLFlowClient

```
import Base.parse
function Base.parse(::Type{Int64}, val::Int64)
    return val
end

using MLFlowClient
```

I have traced the error to the constructor call of MLFlowRunInfo (https://github.com/JuliaAI/MLFlowClient.jl/blob/main/src/types.jl#L115) which receives a dictionary. 
In my case, the HTTP response dictionary contains a start_time entry of type a Int64, causing the subsequent parse call to fail.

**Comment by deyandyankov** [comment]
Thank you very much for raising this and the analysis that you've done. I'll have a look later today and try to release a fix in the evening.

**Comment by jaschau** [comment]
Great! Thanks a lot for the support and the quick response!

**Comment by deyandyankov** [comment]
I think this may already be fixed in `MLFlowClient v0.3` which was released 2 days ago. Can you confirm which version are you using?
I added your code to a test in the following PR and it seems to create a run object correctly:
https://github.com/JuliaAI/MLFlowClient.jl/pull/18/files#diff-7bb5f19705fed4da2dc94504da771911e578a25bbe0285dec35d9b72f5d26bf5

From the automated tests that ran as part of this PR:
```
Test Summary: | Pass  Total  Time
Issue17       |    1      1  0.3s
```

**Comment by jaschau** [comment]
Hi, I have verified that my code fails both with MLFlowClient 0.3 and MLFlowClient 0.2. I have the impression that the failure is not caused by the additional tags. In fact, it is simply the result of the create run REST call (https://mlflow.org/docs/latest/rest-api.html#id71) which returns a RunInfo object (https://mlflow.org/docs/latest/rest-api.html#mlflowruninfo). Interestingly, it even states in the RunInfo documentation linked above that start_time and end_time are of type INT64, unlike the other parameters which are strings. So it looks like the current implementation assumes that start_time and end_time are strings which contradicts the spec.

**Comment by deyandyankov** [comment]
I see what the problem is. My tests were running against `MLFlow 1.21.0` whereas you must have `MLFlow 1.22.0`. I tried 1.22.0 and my tests are failing with your error message. Investigating now, fix to follow soon.

**Comment by jaschau** [comment]
I see, that makes sense :)! Thanks for the help!

**Comment by deyandyankov** [comment]
I've released `v0.3.1` with the fix - please confirm if it works for you :)

**Comment by jaschau** [comment]
That being said, could this potentially be a version issue with

**Comment by jaschau** [comment]
Sorry for the late reply - I tested it and it works like a charm. Thanks again for the support!
