### ISSUE TITLE
Incorrect start time displayed on MLFlow dashboard

### ISSUE THREAD

**Issue by yezhengkai** [JuliaAI/MLFlowClient.jl#20]
The MLFlow REST API [Create Run](https://mlflow.org/docs/latest/rest-api.html#create-run) and [Update Run](https://mlflow.org/docs/latest/rest-api.html#update-run) documentation shows that `start_time` and `end_time` should be Unix timestamp. 

And from [Converting Date/Time without time zone information](https://juliatime.github.io/TimeZones.jl/stable/conversions/#Converting-Date/Time-without-time-zone-information-1) and https://github.com/mlflow/mlflow/issues/30#issuecomment-396094191, we know that Unix timestamp should be UTC+0.

But `createrun` and `updaterun` are using local time, causing the wrong time to be displayed on MLFlow dashboard.

https://github.com/JuliaAI/MLFlowClient.jl/blob/7c88ec42fc3c4c30690454fa8876befe4afe6bcc/src/runs.jl#L17-L24
https://github.com/JuliaAI/MLFlowClient.jl/blob/7c88ec42fc3c4c30690454fa8876befe4afe6bcc/src/runs.jl#L64-L77

**Comment by pebeto** [comment]
The displayed start_time in dashboard is related to the local machine timezone. We are not being able to modify that date unless we scale this issue to [MLFlow](https://github.com/mlflow/mlflow).
Julia has a native way to get the UTC-0 just by passing `UTC` as parameter in `now()` (like in #25).
