### ISSUE TITLE
Can't create experiment with v0.5.1

### ISSUE THREAD

**Issue by cyril-data** [JuliaAI/MLFlowClient.jl#46]
Hi, 

The example [simple-with-mlflow.jl](https://github.com/JuliaAI/MLFlowClient.jl/blob/v0.4.7/examples/simple-with-mlflow.jl) do not work anymore with v0.5.1 : 

```
ERROR: LoadError: HTTP.ConnectError for url = `http://localhost:5000/2.0/mlflow/experiments/create`: IOError: connect: connection refused (ECONNREFUSED)
```

But it's fine with v0.4.7. 

Don't understand why, for now, I downgrade to v0.4.7. 

Looking forward to hearing back from you, I wish you good luck.

**Comment by ablaom** [comment]
@cyril-data Thanks for reporting!

I think something like `mlf = MLFlow("http://localhost:5000")` should now be `mlf = MLFlow("http://localhost:5000/api")`. Does that help?

@pebeto Looks like the example needs updating. Perhaps adding an explicit example call in the Release Notes would also be helpful.
