### ISSUE TITLE
Simplify methods

### ISSUE THREAD

**Issue by characat0** [JuliaAI/MLFlowClient.jl#57]
Right now most of the methods expect to receive instances of MLFlow, MLFlowExperiment and/or MLFlowRunInfo.
This makes calls unnecessarily verbose, as opposed to the python client, that manages a global state.

From our [docs](https://juliaai.github.io/MLFlowClient.jl/dev/tutorial/)
```jl
using MLFlowClient

# Create MLFlow instance
mlf = MLFlow("http://localhost:5000/api")

# Initiate new experiment
experiment_id = createexperiment(mlf; name="price-paths")
exprun = createrun(mlf, experiment_id)

logmetric(mlf, exprun, "pricepath", pricepath)
```

From the [MLflow Tracking QuickStart Guide](https://mlflow.org/docs/latest/getting-started/intro-quickstart/index.html)
```py
import mlflow

# Set our tracking server uri for logging
mlflow.set_tracking_uri(uri="http://127.0.0.1:8080")

# Create a new MLflow Experiment
mlflow.set_experiment("MLflow Quickstart")

# Start an MLflow run
with mlflow.start_run():
    # Log the hyperparameters
    mlflow.log_params(params)

    # Log the loss metric
    mlflow.log_metric("accuracy", accuracy)

```

The Python API is more concise, and the context manager also takes care of finishing the run even if the code inside fails.
If its something desirable, I can start working on adding extra methods for simplifying our API.

**Comment by pebeto** [comment]
Hello @characat0.

The approach of `MLFlowClient.jl` is just to be a client, enabling direct communication to the `mlflow` instance REST API. This approach is followed to enable other ML platforms, just like `MLJ.jl`, to use it and take care of the context (see `MLJFlow.jl`).
Also we are trying to avoid "black magic" by stay pure functional.

I'm open to discuss this if you have a concern.

**Comment by characat0** [comment]
It is mostly syntactic sugar tbh, the same can be accomplished by a wrapper, maybe MLJFlow.jl is more suited for this discussion as you suggested.
